# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "make build-wasm"
bin = "bin/go-app-table"
full_bin = "./bin/go-app-table"
include_ext = ["go", "html", "css"]
exclude_dir = ["bin", "tmp", "vendor", "web/wasm"]
delay = 1000 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"